apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktestflow
  labels:
    app: aktestflow
  namespace: namespace-workflow-1685907319086
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktestflow
  template:
    metadata:
      labels:
        app: aktestflow
    spec:
      containers:
        - name: aktestflow
          image: akhanacr.azurecr.io/academowfl:latest
          ports:
            - containerPort: 8080