apiVersion: v1
kind: Service
metadata:
  name: aktestflow
  namespace: namespace-workflow-1685907319086
spec:
  type: LoadBalancer
  selector:
    app: aktestflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080