apiVersion: v1
kind: Service
metadata:
  name: akdemok8ds
  namespace: aktest
spec:
  type: LoadBalancer
  selector:
    app: akdemok8ds
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080